### PR TITLE
New function to help resolve not-found files/directories

### PR DESCRIPTION
**Pull request by axelalex2**
My personal setup uses symbolic links to save a little bit of space, unfortunately php does not recognize these symbolic links as the OS does. Shortening the path of /../-parts does help, but there is no php-builtin function to do it.
So, this function is straight up copied from the first comment of https://www.php.net/manual/de/function.realpath.php , which you then can use to determine the full path of a file/directory without depending on the functionality of symbolic links.
Would be great if you could accept the pull request, if not, i will get around it with a Plugin-Utils-Class.

### CODE REVIEW

**Comment by kremsy** [comment]
Thanks for your contributions, If everything works I would love to merge, unfortunately, I have currently no time to test the changes.

**Comment by kremsy** [comment]
I don't get the request compeltely as there are 12 commits, are these all needed for this change?

**Comment by axelalex2** [comment]
oh weird; no actually not, but sometimes i don't quite understand the pull request function in github, it's a little easier in gitlab.

**Comment by kremsy** [comment]
Its fine, they are just alöready mergewd commits^^

**Pull request merged**
